// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6XQ2xG0een1NB50VLfIx8vRWwGNBC2fM',
    appId: '1:225366500550:web:ef25223c319829d491a3c7',
    messagingSenderId: '225366500550',
    projectId: 'chatbot-bbf51',
    authDomain: 'chatbot-bbf51.firebaseapp.com',
    storageBucket: 'chatbot-bbf51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXtp0jhzlU_O-JW2L_35R7FrLEkfUvMiY',
    appId: '1:225366500550:android:b44b40650dac8ee391a3c7',
    messagingSenderId: '225366500550',
    projectId: 'chatbot-bbf51',
    storageBucket: 'chatbot-bbf51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQPwyySuNyYqPxqHm2yvfiFqxt5j8jMmU',
    appId: '1:225366500550:ios:f1326c520ed9b22791a3c7',
    messagingSenderId: '225366500550',
    projectId: 'chatbot-bbf51',
    storageBucket: 'chatbot-bbf51.appspot.com',
    iosBundleId: 'com.tassist.tecza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQPwyySuNyYqPxqHm2yvfiFqxt5j8jMmU',
    appId: '1:225366500550:ios:f1326c520ed9b22791a3c7',
    messagingSenderId: '225366500550',
    projectId: 'chatbot-bbf51',
    storageBucket: 'chatbot-bbf51.appspot.com',
    iosBundleId: 'com.tassist.tecza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6XQ2xG0een1NB50VLfIx8vRWwGNBC2fM',
    appId: '1:225366500550:web:13395b7595844c9f91a3c7',
    messagingSenderId: '225366500550',
    projectId: 'chatbot-bbf51',
    authDomain: 'chatbot-bbf51.firebaseapp.com',
    storageBucket: 'chatbot-bbf51.appspot.com',
  );
}
